# Generated by Django 4.1.5 on 2023-04-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palette", "0002_alter_spritesheet_options_remove_outfit_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wardrobe",
            name="gravity_suit",
        ),
        migrations.RemoveField(
            model_name="wardrobe",
            name="power_suit",
        ),
        migrations.RemoveField(
            model_name="wardrobe",
            name="varia_suit",
        ),
        migrations.AddField(
            model_name="wardrobe",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
