# Generated by Django 4.1.5 on 2023-04-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("palette", "0003_remove_wardrobe_gravity_suit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Outfit",
        ),
    ]
